<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>disable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<LangVersion>latest</LangVersion>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<RootNamespace>RzR.ResultMessage.Web.Tests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.4.3" />
		<PackageReference Include="MSTest.TestFramework" Version="3.4.3" />
		<PackageReference Include="coverlet.collector" Version="6.0.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\AggregatedGenericResultMessage.Web\AggregatedGenericResultMessage.Web.csproj" />
	</ItemGroup>

</Project>
