<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net5.0;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Authors>RzR</Authors>
		<Copyright>RzR</Copyright>
		<Owners>RzR</Owners>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageIcon>PackageIcon.png</PackageIcon>
		<NoWarn>$(NoWarn);CS8032</NoWarn>
		<EnableNETAnalyzers>false</EnableNETAnalyzers>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageTags>Result;ResultMessage;API;ReturnMessage;Response;SOAP;Service;Web</PackageTags>
		<RepositoryUrl>https://github.com/I-RzR-I/AggregatedGenericResultMessage-Web</RepositoryUrl>
		<PackageProjectUrl>https://github.com/I-RzR-I/AggregatedGenericResultMessage-Web</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageDescription>This library is an aggregate of some extensions to use more comfortable `Result lib`. In other words, transform from `Result` to `IActionResult`.</PackageDescription>
		<Summary>This library is an aggregate of some extensions to use more comfortable `Result lib`. In other words, transform from `Result` to `IActionResult`.</Summary>
		<PackageTitle>RzR.Shared.ResultMessage (AggregatedGenericResultMessage.Web)</PackageTitle>
		<Title>RzR.Shared.ResultMessage (AggregatedGenericResultMessage.Web)</Title>
		<LangVersion>latest</LangVersion><!--9.0-->
		<RepositoryType>GIT</RepositoryType>
		<Language>en-US</Language>
		
		<RootNamespace>RzR.ResultMessage.Web</RootNamespace>
		<AssemblyName>RzR.ResultMessage.Web</AssemblyName>
		
		<PackageReleaseNotes>

		</PackageReleaseNotes>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\shared\GeneralAssemblyInfo.cs" Link="Properties\GeneralAssemblyInfo.cs" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="RzR.ResultMessage" Version="3.0.0.6928" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
		<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.3" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.32" />
	</ItemGroup>

	<ItemGroup Condition="
			   '$(TargetFramework)' == 'net5.0' 
			   Or '$(TargetFramework)' == 'net6.0' 
			   Or '$(TargetFramework)' == 'net7.0' 
			   Or '$(TargetFramework)' == 'net8.0' 
			   Or '$(TargetFramework)' == 'net9.0'">
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\..\assets\PackageIcon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
		<None Include="..\.editorconfig" />
	</ItemGroup>
	<ProjectExtensions>
		<VisualStudio>
			<UserProperties BuildVersion_StartDate="2023/6/10" />
		</VisualStudio>
	</ProjectExtensions>
	<!--<Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="PowerShell -NoProfile -ExecutionPolicy unrestricted -file $(SolutionDir)../build/pack.ps1 $(ConfigurationName)" />
  </Target>-->

</Project>